matrix:
  include:
    - language: python
      python: 3.7
      name: Linux
      os: linux
      dist: xenial
      sudo: true
    - language: generic
      name: OS X
      os: osx
      before_install:
        - brew update && brew install python3
    - 

install:
  - python --version
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest