language: python

matrix:
  include:
    - name: Linux
      os: linux
      dist: xenial
      sudo: true
    - name: OS X
      os: osx
      before_install:
        - brew update && brew install python3

install:
  - python --version
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest